name: IBM Cloud Auto Restart 

on:
  push:
    branches: [ master ]
  schedule:
    - cron: '0 12 * * FRI'

jobs:
  ibm-cloud-restart:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Init
      run: |
        chmod -R 777 ./IBM_Cloud_CLI/
        ./IBM_Cloud_CLI/ibmcloud config --check-version=false
    - name: Login IBM Cloud
      env:
        IBM_ACCOUNT: ${{ secrets.IBM_ACCOUNT }}
        REGION_NUM: ${{ secrets.REGION_NUM }}
      run: |
        
